
title: Lekan Molu #(ぇかん オグンモゥ)
locale: en_US
email: lekanmolu@scriptedonachip.com #olalekan.ogunmolu@pennmedicine.upenn.edu
description: > # this means to ignore newlines until "baseurl:"  > #  Still Attacking Cancer
        Rerum Cognoscere Causas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scriptedonachip.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: robotsorcerer
github_username:  robotsorcerer
docker_username:  robotsorcerer
timezone:         America/New-York
quora_username:   Lekan-Molu
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: "_quotes/quote_files"
    values:
      static: "true"
markdown: kramdown
plugins:
  - jekyll-watch
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
  - .travis.yml
  - validate.rb
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
  
# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
