
title: Lekan Molu #(ぇかん オグンモゥ)
locale: en_US
email: olalekan.ogunmolu@pennmedicine.upenn.edu
description: > # this means to ignore newlines until "baseurl:"  > #  Still Attacking Cancer
        To discover and understand
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scriptedonachip.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: therobosorcerer
github_username:  lakehanne
docker_username:  lakehanne
phone: +1-215-898-5088
timezone:         America/Chicago
quora_username:   Olalekan-Ogunmolu
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: "_quotes/quote_files"
    values:
      static: "true"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-watch
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
  - .travis.yml
  - jekyll-feed
  - me-style.jpg
  - validate.rb
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
